# -*- coding: utf-8 -*-

###############################################################################
#                                                                             #
# Copyright 2015.  Los Alamos National Security, LLC. This material was       #
# produced under U.S. Government contract DE-AC52-06NA25396 for Los Alamos    #
# National Laboratory (LANL), which is operated by Los Alamos National        #
# Security, LLC for the U.S. Department of Energy. The U.S. Government has    #
# rights to use, reproduce, and distribute this software.  NEITHER THE        #
# GOVERNMENT NOR LOS ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY,        #
# EXPRESS OR IMPLIED, OR ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.  #
# If software is modified to produce derivative works, such modified software #
# should be clearly marked, so as not to confuse it with the version          #
# available from LANL.                                                        #
#                                                                             #
# Additionally, this program is free software; you can redistribute it and/or #
# modify it under the terms of the GNU General Public License as published by #
# the Free Software Foundation; either version 2 of the License, or (at your  #
# option) any later version. Accordingly, this program is distributed in the  #
# hope that it will be useful, but WITHOUT ANY WARRANTY; without even the     #
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.    #
# See the GNU General Public License for more details.                        #
#                                                                             #
###############################################################################

# Form implementation generated from reading ui file 'dylan_main_listview.ui'
#
# Created: Mon Jun 18 17:03:45 2012
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 720)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setContentsMargins(2, 2, 3, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtGui.QFrame.Raised)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.rule_list_widget = QtGui.QListWidget(self.splitter)
        self.rule_list_widget.setMinimumSize(QtCore.QSize(250, 0))
        self.rule_list_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rule_list_widget.setFrameShape(QtGui.QFrame.Box)
        self.rule_list_widget.setFrameShadow(QtGui.QFrame.Plain)
        self.rule_list_widget.setDragEnabled(False)
        self.rule_list_widget.setAlternatingRowColors(True)
        self.rule_list_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.rule_list_widget.setLayoutMode(QtGui.QListView.SinglePass)
        self.rule_list_widget.setViewMode(QtGui.QListView.ListMode)
        self.rule_list_widget.setSelectionRectVisible(True)
        self.rule_list_widget.setObjectName("rule_list_widget")
        self.frame_rule_details = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_rule_details.sizePolicy().hasHeightForWidth())
        self.frame_rule_details.setSizePolicy(sizePolicy)
        self.frame_rule_details.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_rule_details.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_rule_details.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_rule_details.setObjectName("frame_rule_details")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_rule_details)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_right_side = QtGui.QSplitter(self.frame_rule_details)
        self.splitter_right_side.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter_right_side.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter_right_side.setOrientation(QtCore.Qt.Vertical)
        self.splitter_right_side.setOpaqueResize(True)
        self.splitter_right_side.setObjectName("splitter_right_side")
        self.rule_info = QtGui.QFrame(self.splitter_right_side)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rule_info.sizePolicy().hasHeightForWidth())
        self.rule_info.setSizePolicy(sizePolicy)
        self.rule_info.setMinimumSize(QtCore.QSize(0, 250))
        self.rule_info.setFrameShape(QtGui.QFrame.Box)
        self.rule_info.setFrameShadow(QtGui.QFrame.Plain)
        self.rule_info.setObjectName("rule_info")
        self.verticalLayout = QtGui.QVBoxLayout(self.rule_info)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rule_action_frame = QtGui.QFrame(self.rule_info)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rule_action_frame.sizePolicy().hasHeightForWidth())
        self.rule_action_frame.setSizePolicy(sizePolicy)
        self.rule_action_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rule_action_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.rule_action_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.rule_action_frame.setObjectName("rule_action_frame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.rule_action_frame)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rule_name_label = QtGui.QLabel(self.rule_action_frame)
        self.rule_name_label.setObjectName("rule_name_label")
        self.horizontalLayout_3.addWidget(self.rule_name_label)
        spacerItem = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.report_button = QtGui.QPushButton(self.rule_action_frame)
        self.report_button.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.report_button.sizePolicy().hasHeightForWidth())
        self.report_button.setSizePolicy(sizePolicy)
        self.report_button.setFlat(False)
        self.report_button.setObjectName("report_button")
        self.horizontalLayout_3.addWidget(self.report_button)
        self.fix_button = QtGui.QPushButton(self.rule_action_frame)
        self.fix_button.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fix_button.sizePolicy().hasHeightForWidth())
        self.fix_button.setSizePolicy(sizePolicy)
        self.fix_button.setObjectName("fix_button")
        self.horizontalLayout_3.addWidget(self.fix_button)
        self.revert_button = QtGui.QPushButton(self.rule_action_frame)
        self.revert_button.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.revert_button.sizePolicy().hasHeightForWidth())
        self.revert_button.setSizePolicy(sizePolicy)
        self.revert_button.setObjectName("revert_button")
        self.horizontalLayout_3.addWidget(self.revert_button)
        self.verticalLayout.addWidget(self.rule_action_frame)
        self.rule_desc_res_scrollarea = QtGui.QScrollArea(self.rule_info)
        self.rule_desc_res_scrollarea.setFrameShape(QtGui.QFrame.NoFrame)
        self.rule_desc_res_scrollarea.setWidgetResizable(True)
        self.rule_desc_res_scrollarea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.rule_desc_res_scrollarea.setObjectName("rule_desc_res_scrollarea")
        self.rule_desc_scrollAreaWidgetContents = QtGui.QWidget(self.rule_desc_res_scrollarea)
        self.rule_desc_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 696, 404))
        self.rule_desc_scrollAreaWidgetContents.setObjectName("rule_desc_scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.rule_desc_scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rule_desc_label = QtGui.QLabel(self.rule_desc_scrollAreaWidgetContents)
        self.rule_desc_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.rule_desc_label.setObjectName("rule_desc_label")
        self.verticalLayout_2.addWidget(self.rule_desc_label)
        self.rule_instructions_text = QtGui.QTextEdit(self.rule_desc_scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rule_instructions_text.sizePolicy().hasHeightForWidth())
        self.rule_instructions_text.setSizePolicy(sizePolicy)
        self.rule_instructions_text.setMinimumSize(QtCore.QSize(0, 100))
        self.rule_instructions_text.setFrameShape(QtGui.QFrame.NoFrame)
        self.rule_instructions_text.setFrameShadow(QtGui.QFrame.Plain)
        self.rule_instructions_text.setLineWidth(0)
        self.rule_instructions_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.rule_instructions_text.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.rule_instructions_text.setObjectName("rule_instructions_text")
        self.verticalLayout_2.addWidget(self.rule_instructions_text)
        self.rule_results_label = QtGui.QLabel(self.rule_desc_scrollAreaWidgetContents)
        self.rule_results_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.rule_results_label.setObjectName("rule_results_label")
        self.verticalLayout_2.addWidget(self.rule_results_label)
        self.rule_results_text = QtGui.QPlainTextEdit(self.rule_desc_scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rule_results_text.sizePolicy().hasHeightForWidth())
        self.rule_results_text.setSizePolicy(sizePolicy)
        self.rule_results_text.setMinimumSize(QtCore.QSize(0, 100))
        self.rule_results_text.setFrameShape(QtGui.QFrame.NoFrame)
        self.rule_results_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.rule_results_text.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.rule_results_text.setObjectName("rule_results_text")
        self.verticalLayout_2.addWidget(self.rule_results_text)
        self.rule_desc_res_scrollarea.setWidget(self.rule_desc_scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.rule_desc_res_scrollarea)
        self.outer_conf_item_frame = QtGui.QFrame(self.splitter_right_side)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outer_conf_item_frame.sizePolicy().hasHeightForWidth())
        self.outer_conf_item_frame.setSizePolicy(sizePolicy)
        self.outer_conf_item_frame.setMinimumSize(QtCore.QSize(0, 250))
        self.outer_conf_item_frame.setFrameShape(QtGui.QFrame.Box)
        self.outer_conf_item_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.outer_conf_item_frame.setObjectName("outer_conf_item_frame")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.outer_conf_item_frame)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.conf_items_scroll_area = QtGui.QScrollArea(self.outer_conf_item_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conf_items_scroll_area.sizePolicy().hasHeightForWidth())
        self.conf_items_scroll_area.setSizePolicy(sizePolicy)
        self.conf_items_scroll_area.setFrameShape(QtGui.QFrame.NoFrame)
        self.conf_items_scroll_area.setWidgetResizable(True)
        self.conf_items_scroll_area.setObjectName("conf_items_scroll_area")
        self.configitem_scrollarea = QtGui.QWidget(self.conf_items_scroll_area)
        self.configitem_scrollarea.setGeometry(QtCore.QRect(0, 0, 696, 203))
        self.configitem_scrollarea.setObjectName("configitem_scrollarea")
        self.conf_items_scroll_area.setWidget(self.configitem_scrollarea)
        self.verticalLayout_8.addWidget(self.conf_items_scroll_area)
        self.save_cancel_frame = QtGui.QFrame(self.outer_conf_item_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_cancel_frame.sizePolicy().hasHeightForWidth())
        self.save_cancel_frame.setSizePolicy(sizePolicy)
        self.save_cancel_frame.setMinimumSize(QtCore.QSize(0, 45))
        self.save_cancel_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.save_cancel_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.save_cancel_frame.setObjectName("save_cancel_frame")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.save_cancel_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.save_button = QtGui.QPushButton(self.save_cancel_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_6.addWidget(self.save_button)
        self.cancel_button = QtGui.QPushButton(self.save_cancel_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_6.addWidget(self.cancel_button)
        self.verticalLayout_8.addWidget(self.save_cancel_frame)
        self.verticalLayout_3.addWidget(self.splitter_right_side)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        #####
        # start menu creation
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuRule = QtGui.QMenu(self.menubar)
        self.menuRule.setObjectName("menuRule")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")

        MainWindow.setMenuBar(self.menubar)

        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")

        self.actionLog = QtGui.QAction(MainWindow)
        self.actionLog.setObjectName("actionLog")
        self.actionLog.setShortcut('Ctrl+L')
        # Commented out setStatusTip calls to keep them from stomping on run
        # messages
        #self.actionLog.setStatusTip('View Run Log')
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionQuit.setObjectName("actionQuit")
        self.actionQuit.setShortcut('Ctrl+Q')
        #self.actionQuit.setStatusTip('Quit application')

        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.actionRun_All = QtGui.QAction(MainWindow)
        self.actionRun_All.setObjectName("actionRun_All")
        self.actionRun_All.setShortcut('Ctrl+R')

        #self.actionRun_All.setStatusTip('Run Fix All')
        self.actionReport_All = QtGui.QAction(MainWindow)
        self.actionReport_All.setObjectName("actionReport_All")
        self.actionReport_All.setShortcut('Ctrl+G')

        #self.actionReport_All.setStatusTip('Run Report All')
        self.actionRevert_All = QtGui.QAction(MainWindow)
        self.actionRevert_All.setObjectName("actionRevert_All")

        #self.actionRevert_All.setStatusTip('Attempt to Revert All Changes')
        #self.actionEdit_Selected = QtGui.QAction(MainWindow)
        #self.actionEdit_Selected.setObjectName("actionEdit_Selected")

        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionStop.setShortcut('Ctrl+K')
        #self.actionStop.setStatusTip('Stop Current Run')
        self.menuFile.addAction(self.actionLog)

        self.actionGuiHelp = QtGui.QAction(MainWindow)
        self.actionGuiHelp.setObjectName("actionGuiHelp")
        self.actionGuiHelp.setShortcut('Ctrl+H')
        self.menuHelp.addAction(self.actionGuiHelp)

        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuRule.addAction(self.actionRun_All)
        self.menuRule.addAction(self.actionReport_All)
        self.menuRule.addAction(self.actionRevert_All)
        self.menuRule.addAction(self.actionStop)
        #self.menuRule.addAction(self.actionEdit_Selected)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRule.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "STONIX", None, QtGui.QApplication.UnicodeUTF8))
        self.rule_name_label.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">[Rule Name]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.report_button.setText(QtGui.QApplication.translate("MainWindow", "Report", None, QtGui.QApplication.UnicodeUTF8))
        self.revert_button.setText(QtGui.QApplication.translate("MainWindow", "Revert", None, QtGui.QApplication.UnicodeUTF8))
        self.fix_button.setText(QtGui.QApplication.translate("MainWindow", "Fix", None, QtGui.QApplication.UnicodeUTF8))
        self.rule_desc_label.setText(QtGui.QApplication.translate("MainWindow", "Rule Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.rule_instructions_text.setPlainText(QtGui.QApplication.translate("MainWindow", "sdf\n"
"sdf\n"
"sdf\n"
"sdf", None, QtGui.QApplication.UnicodeUTF8))
        self.rule_results_label.setText(QtGui.QApplication.translate("MainWindow", "Results:", None, QtGui.QApplication.UnicodeUTF8))
        self.rule_results_text.setPlainText(QtGui.QApplication.translate("MainWindow", "sdf\n"
"sdf\n"
"sdf\n"
"sdf", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRule.setTitle(QtGui.QApplication.translate("MainWindow", "Rule", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog.setText(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_All.setText(QtGui.QApplication.translate("MainWindow", "Fix All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport_All.setText(QtGui.QApplication.translate("MainWindow", "Report All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRevert_All.setText(QtGui.QApplication.translate("MainWindow", "Revert All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "Stop Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuiHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        # self.actionEdit_Selected.setText(QtGui.QApplication.translate("MainWindow", "Edit Selected", None, QtGui.QApplication.UnicodeUTF8))

