#!/usr/bin/python
###############################################################################
#                                                                             #
# Copyright 2015-2019.  Los Alamos National Security, LLC. This material was       #
# produced under U.S. Government contract DE-AC52-06NA25396 for Los Alamos    #
# National Laboratory (LANL), which is operated by Los Alamos National        #
# Security, LLC for the U.S. Department of Energy. The U.S. Government has    #
# rights to use, reproduce, and distribute this software.  NEITHER THE        #
# GOVERNMENT NOR LOS ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY,        #
# EXPRESS OR IMPLIED, OR ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.  #
# If software is modified to produce derivative works, such modified software #
# should be clearly marked, so as not to confuse it with the version          #
# available from LANL.                                                        #
#                                                                             #
# Additionally, this program is free software; you can redistribute it and/or #
# modify it under the terms of the GNU General Public License as published by #
# the Free Software Foundation; either version 2 of the License, or (at your  #
# option) any later version. Accordingly, this program is distributed in the  #
# hope that it will be useful, but WITHOUT ANY WARRANTY; without even the     #
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.    #
# See the GNU General Public License for more details.                        #
#                                                                             #
###############################################################################
import os
import shutil
import sys

TARGET_LOCATION = sys.argv[2]


def removeOldStonix(target):
    try:
        shutil.rmtree(target)
    except OSError:
        print "Could not find " + str(target)
    return 0

def backupOldStonixConf(target):
    '''
    If the target conf file exists, stonix will be using it to save the users
    settings, regarless of whether or not /etc/stonix.conf exists. Newer
    versions of stonix will no longer put a conf file in the application path,
    so this should now be moved to /etc.
    '''
    conffile = target + "/Contents/Resources/stonix.app/Contents/" + \
        "Resources/stonix.conf"
    if os.path.exists(conffile) and not os.path.islink(conffile):
        os.rename(conffile, "/etc/stonix.conf")


if __name__ == "__main__":
    target = os.path.join(TARGET_LOCATION + "Applications/stonix4mac.app")
    backupOldStonixConf(target)
    sys.exit(removeOldStonix(target))
