#!/bin/zsh
###############################################################################
#                                                                             #
# Copyright 2019. Triad National Security, LLC. All rights reserved.          #
# This program was produced under U.S. Government contract 89233218CNA000001  #
# for Los Alamos National Laboratory (LANL), which is operated by Triad       #
# National Security, LLC for the U.S. Department of Energy/National Nuclear   #
# Security Administration.                                                    #
#                                                                             #
# All rights in the program are reserved by Triad National Security, LLC, and #
# the U.S. Department of Energy/National Nuclear Security Administration. The #
# Government is granted for itself and others acting on its behalf a          #
# nonexclusive, paid-up, irrevocable worldwide license in this material to    #
# reproduce, prepare derivative works, distribute copies to the public,       #
# perform publicly and display publicly, and to permit others to do so.       #
#                                                                             #
###############################################################################

set -e

TARGET_LOCATION=${1}Applications/stonix4mac.app
CONF_FILE=${TARGET_LOCATION}/Contents/Resources/stonix.app/Contents/Resources/stonix.conf

# Copy stonix.conf to etc
if [[ -a ${CONF_FILE} ]]; then
    cp ${CONF_FILE} /etc/stonix.conf
fi

# Remove old installation of stonix
if [[ -a ${TARGET_LOCATION} ]]; then
    rm -rf ${TARGET_LOCATION}
fi
